Import("env")

# copy files to root
for p in [
    "site.webmanifest",
    "browserconfig.xml",
    "favicon.ico"
]:
    env.Command('#/$BLD/' + p, "build/" + p, Copy('$TARGET', '$SOURCE'))

# copy images
for p in [
    "android-chrome-192x192.png",
    "android-chrome-512x512.png",
    "apple-touch-icon.png",
    "favicon-16x16.png",
    "favicon-32x32.png",
    "mstile-310x310.png",
    "safari-pinned-tab.svg",
]:
    env.Command('#/$BLD/img/' + p, "build/" + p, Copy('$TARGET', '$SOURCE'))
