variables:
  GIT_STRATEGY: fetch

before_script:
  - if [ -z "$DEPLOY_PATH" ]; then echo "Project variable DEPLOY_PATH is not defined"; exit 1; fi

stages:
  - stage_example

job_example:
  only:
    - main
  stage: stage_example
  script:
    - git status
