# unfortunately, we cannot integrate this into pyproject.toml or package.json

MD051: false # Link fragments should be valid
MD041: false # First line in a file should be a top-level heading
MD013:
  line_length: 88
  tables: false # Allow longer lines in tables
  code_blocks: false # Allow longer lines in code blocks
MD026: false # trailing punctuation in heading
