import os

from SCons.Script import Export  # type:ignore
from SCons.Script import Environment, SConscript

env = Environment(
    ENV=os.environ,
    DEBUG=True,
    SRC="src",
    BLD="build",
    TMP="temp",
)
env.Decider("MD5-timestamp")
env.Clean("all", ["$TMP", "$BLD"])


Export("env")  # export environment before including SConscript

SConscript("SConscript")
