exclude: ^.*(.min.js|.min.css)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"] # because of tags in mkdocs.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(css|less|md|json|sql)$
#  - repo: https://github.com/pre-commit/mirrors-eslint
#    rev: v9.0.0-beta.2
#    hooks:
#      - id: eslint
#        additional_dependencies:
#          - eslint-config-prettier@9.1.0
#          - eslint-plugin-prettier@5.1.3
#        args: ["--fix"]
