import os
from glob import glob
from SCons.Script import Environment

env = Environment(
    ENV=os.environ,
    # SRC="src",
    # BUILD="dist",
    # TMP=".tmp",
    # PYSTACHE_JSON='pystache-cli $TARGET $SOURCE --strict --separators \\"{{ }}\\"',
)
# env.Decider("timestamp-newer")
env.Decider("MD5")  # timestamp-newer MD5-timestamp
# env.Clean("all", ["$BUILD", "$TMP"])

# env.Export("env")
# env.SConscript(env.GetBuildPath("#/src/appData/SConscript"))

functions_js = env.Command(
    "src/appData/build/functions.js",
    "src/appData/buildFunctions.cjs",
    "node $SOURCE src/appData/functions $TARGET",
)
env.Depends(functions_js, glob("src/appData/functions/**/*.js", recursive=True))


data_json = env.Command(
    "src/appData/build/data.json",
    "src/appData/buildData.py",
    "python $SOURCE src/appData/data $TARGET",
)
env.Depends(data_json, glob("src/appData/data/**/*.json", recursive=True))

ui_js = env.Command(
    "src/appData/build/ui.js",
    "src/appData/buildUI.py",
    "python $SOURCE src/appData/ui $TARGET",
)
env.Depends(ui_js, glob("src/appData/ui/**/*.json", recursive=True))
env.Depends(ui_js, glob("src/appData/components/**/*", recursive=True))
