import os
from glob import glob
from SCons.Script import Environment

env = Environment(
    ENV=os.environ,
    # SRC="src",
    # BUILD="dist",
    # TMP=".tmp",
    # PYSTACHE_JSON='pystache-cli $TARGET $SOURCE --strict --separators \\"{{ }}\\"',
)
# env.Decider("timestamp-newer")
env.Decider("MD5")  # timestamp-newer MD5-timestamp
# env.Clean("all", ["$BUILD", "$TMP"])

# env.Export("env")
# env.SConscript(env.GetBuildPath("#/src/appData/SConscript"))

data_json = env.Command(
    "src/appData/build/data.json",
    "src/buildtools/buildData.py",
    "python $SOURCE src/appData/data $TARGETS",
)
env.Depends(data_json, glob("src/appData/data/**/*.json", recursive=True))


functions_js = env.Command(
    "src/appData/build/functions.js",
    ["src/buildtools/buildFunctions.cjs", "src/appData/build/data.json"],
    "node $SOURCES src/appData/functions $TARGET",
)
env.Depends(functions_js, glob("src/appData/functions/**/*.js", recursive=True))


ui_js = env.Command(
    "src/appData/build/ui.js",
    ["src/buildtools/buildUI.cjs", "src/index.html"],
    "node $SOURCES src/appData/ui $TARGET",
)
env.Depends(ui_js, glob("src/appData/ui/**/*.js", recursive=True))
env.Depends(ui_js, glob("src/components/**/*", recursive=True))
