# Generated by Django 5.0.6 on 2024-07-11 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExampleDataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("example_key_field_1", models.CharField(max_length=128)),
                ("example_value_field_1", models.FloatField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="main.upload"
                    ),
                ),
            ],
            options={
                "unique_together": {("upload", "example_key_field_1")},
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=128)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "key")},
            },
        ),
    ]
