import os

from SCons.Script import Environment

env = Environment(
    ENV=os.environ,
    SRC="src",
    BUILD="build",
    TMP=".tmp",
    PYSTACHE_JSON='pystache-cli $TARGET $SOURCE --strict --separators \\"{{ }}\\"',
)
env.Decider("timestamp-newer")
env.Clean("all", ["$BUILD", "$TMP"])

env.Export("env")
env.SConscript(env.GetBuildPath("SConscript"))
