name: python_test_tox

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - run: |
          conda config --system --set changeps1 False  # fixes conda: UnicodeEncodeError in windows
          conda install -q -y -c conda-forge tox
          conda create -q -y -n py38 python=3.8
          conda create -q -y -n py312 python=3.12
      - run: |
          export PY38_PATH=$CONDA/envs/py38/bin
          export PY312_PATH=$CONDA/envs/py312/bin
          export PATH=$PATH:$PY38_PATH:$PY312_PATH
          tox # --parallel
