"""Create your models here."""

from django.db import models


class Data(models.Model):
    # autogenerated with: python manage.py inspectdb --database=data data
    key = models.CharField(unique=True, max_length=128)
    value = models.TextField(blank=True, null=True)

    class Meta:
        """Model meta attributes."""

        managed = False  # do not change table with migrations
        db_table = "data"  # custom table name
