from django.db import models

# Create your models here.


class Data(models.Model):
    # autogenerated with: python manage.py inspectdb --database=data data
    key = models.CharField(unique=True, max_length=128)
    value = models.TextField(blank=True, null=True)

    class Meta:
        managed = False  # do not change table with migrations
        db_table = "data"  # custom table name
